"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const admin_controller_1 = require("../controllers/admin.controller");
const paymentMethod_controller_1 = require("../controllers/paymentMethod.controller");
const permissions_1 = require("../constants/permissions");
const auth_middleware_1 = require("../middlewares/auth.middleware");
const rbac_middleware_1 = require("../middlewares/rbac.middleware");
const router = (0, express_1.Router)();
router.use(auth_middleware_1.requireAuth, (0, rbac_middleware_1.requirePermission)(permissions_1.PERMISSIONS.ADMIN_ALL));
router.get("/stats", admin_controller_1.getPlatformStats);
router.post("/users", admin_controller_1.createUserByAdmin);
router.get("/users", admin_controller_1.listUsers);
router.get("/users/assignable", admin_controller_1.listAssignableUsers);
router.get("/owners", admin_controller_1.listOwners);
router.patch("/owners/:ownerId/status", admin_controller_1.updateOwnerStatus);
router.get("/commission", admin_controller_1.getCommission);
router.put("/commission", admin_controller_1.updateCommission);
router.get("/resources", admin_controller_1.listAllResources);
router.put("/resources/:resourceId/commission", admin_controller_1.updateResourceCommission);
router.get("/payment-methods", paymentMethod_controller_1.listPaymentMethods);
router.post("/payment-methods", paymentMethod_controller_1.createPaymentMethod);
router.patch("/payment-methods/:methodId", paymentMethod_controller_1.updatePaymentMethod);
exports.default = router;
