"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const auth_controller_1 = require("../controllers/auth.controller");
const auth_middleware_1 = require("../middlewares/auth.middleware");
const router = (0, express_1.Router)();
router.post("/register", auth_controller_1.register);
router.post("/login", auth_controller_1.login);
router.get("/me", auth_middleware_1.requireAuth, auth_controller_1.getMe);
router.post("/google", auth_controller_1.googleAuthPlaceholder);
router.post("/refresh", auth_controller_1.refreshAccessToken);
router.post("/logout", auth_controller_1.logout);
router.post("/email/send-verification", auth_middleware_1.requireAuth, auth_controller_1.sendEmailVerificationToken);
router.post("/email/verify", auth_controller_1.verifyEmail);
exports.default = router;
