"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const booking_controller_1 = require("../controllers/booking.controller");
const permissions_1 = require("../constants/permissions");
const auth_middleware_1 = require("../middlewares/auth.middleware");
const rbac_middleware_1 = require("../middlewares/rbac.middleware");
const router = (0, express_1.Router)();
router.post("/", auth_middleware_1.requireAuth, (0, rbac_middleware_1.requirePermission)(permissions_1.PERMISSIONS.BOOKING_CREATE), booking_controller_1.createBooking);
router.get("/me", auth_middleware_1.requireAuth, (0, rbac_middleware_1.requirePermission)(permissions_1.PERMISSIONS.BOOKING_VIEW), booking_controller_1.listMyBookings);
router.patch("/me/:bookingId/cancel", auth_middleware_1.requireAuth, (0, rbac_middleware_1.requirePermission)(permissions_1.PERMISSIONS.BOOKING_CREATE), booking_controller_1.cancelMyBooking);
router.post("/me/:bookingId/manual-payment", auth_middleware_1.requireAuth, (0, rbac_middleware_1.requirePermission)(permissions_1.PERMISSIONS.BOOKING_CREATE), booking_controller_1.submitManualPayment);
router.get("/manage", auth_middleware_1.requireAuth, (0, rbac_middleware_1.requirePermission)(permissions_1.PERMISSIONS.BOOKING_VIEW), booking_controller_1.listManagedBookings);
router.get("/manage/resources", auth_middleware_1.requireAuth, (0, rbac_middleware_1.requirePermission)(permissions_1.PERMISSIONS.BOOKING_VIEW), booking_controller_1.listManagedResources);
router.get("/manage/customers", auth_middleware_1.requireAuth, (0, rbac_middleware_1.requirePermission)(permissions_1.PERMISSIONS.BOOKING_UPDATE_STATUS), booking_controller_1.lookupCustomers);
router.post("/manage", auth_middleware_1.requireAuth, (0, rbac_middleware_1.requirePermission)(permissions_1.PERMISSIONS.BOOKING_UPDATE_STATUS), booking_controller_1.createManagedBooking);
router.patch("/:bookingId/manual-review", auth_middleware_1.requireAuth, (0, rbac_middleware_1.requirePermission)(permissions_1.PERMISSIONS.BOOKING_UPDATE_STATUS), booking_controller_1.reviewManualPayment);
router.post("/:bookingId/record-payment", auth_middleware_1.requireAuth, (0, rbac_middleware_1.requirePermission)(permissions_1.PERMISSIONS.BOOKING_UPDATE_STATUS), booking_controller_1.recordBookingPayment);
router.patch("/:bookingId/status", auth_middleware_1.requireAuth, (0, rbac_middleware_1.requirePermission)(permissions_1.PERMISSIONS.BOOKING_UPDATE_STATUS), booking_controller_1.updateBookingStatus);
router.get("/me/:bookingId/invoice", auth_middleware_1.requireAuth, (0, rbac_middleware_1.requirePermission)(permissions_1.PERMISSIONS.BOOKING_VIEW), booking_controller_1.downloadInvoice);
exports.default = router;
