"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const payment_controller_1 = require("../controllers/payment.controller");
const permissions_1 = require("../constants/permissions");
const auth_middleware_1 = require("../middlewares/auth.middleware");
const rbac_middleware_1 = require("../middlewares/rbac.middleware");
const router = (0, express_1.Router)();
router.get("/status", payment_controller_1.getPaymentStatus);
router.get("/me", auth_middleware_1.requireAuth, (0, rbac_middleware_1.requirePermission)(permissions_1.PERMISSIONS.BOOKING_VIEW), payment_controller_1.listMyPayments);
router.get("/manage", auth_middleware_1.requireAuth, (0, rbac_middleware_1.requirePermission)(permissions_1.PERMISSIONS.BOOKING_VIEW), payment_controller_1.listManagedPayments);
router.post("/initiate", auth_middleware_1.requireAuth, (0, rbac_middleware_1.requirePermission)(permissions_1.PERMISSIONS.BOOKING_CREATE), payment_controller_1.initiatePayment);
router.post("/verify", payment_controller_1.verifyPayment);
router.post("/callback/sslcommerz/success", payment_controller_1.sslCommerzSuccessCallback);
router.post("/callback/sslcommerz/fail", payment_controller_1.sslCommerzFailCallback);
router.post("/callback/sslcommerz/cancel", payment_controller_1.sslCommerzCancelCallback);
router.get("/callback/sslcommerz/success", payment_controller_1.sslCommerzSuccessCallback);
router.get("/callback/sslcommerz/fail", payment_controller_1.sslCommerzFailCallback);
router.get("/callback/sslcommerz/cancel", payment_controller_1.sslCommerzCancelCallback);
router.post("/callback/sslcommerz", payment_controller_1.sslCommerzSuccessCallback);
router.post("/webhook/sslcommerz", payment_controller_1.sslCommerzWebhook);
exports.default = router;
