import { PERMISSIONS, type Permission } from "./permissions";
import { ROLES, type Role } from "./roles";

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  [ROLES.USER]: [PERMISSIONS.BOOKING_CREATE, PERMISSIONS.BOOKING_VIEW],
  [ROLES.OWNER]: [
    PERMISSIONS.BOOKING_VIEW,
    PERMISSIONS.SLOT_MANAGE,
    PERMISSIONS.RESOURCE_MANAGE,
    PERMISSIONS.PRICE_MANAGE,
    PERMISSIONS.REFUND_MANAGE,
  ],
  [ROLES.STAFF]: [
    PERMISSIONS.BOOKING_VIEW,
    PERMISSIONS.SLOT_MANAGE,
    PERMISSIONS.BOOKING_UPDATE_STATUS,
    PERMISSIONS.REFUND_MANAGE,
  ],
  [ROLES.ADMIN]: [PERMISSIONS.ADMIN_ALL],
};
